name: Testing
on: 
    push:
        branches:
            - main
    workflow_run:
        workflows: ['Check NextJs build and Linting']
        types: 
          - completed
        branches:
          - main
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:3000"
          component: true
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome