name: Testing
on: 
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_run:
        workflows: ['Check NextJs build and Linting']
        types: [completed]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
      - name: Cypress run
        uses: cypress-io/github-action@v6
   